In [1]:
import lightgbm as lgb
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
#データセットの読み込み
train_dataset = pd.read_csv('train.csv')

In [3]:
train_dataset

id      f_00      f_01      f_02      f_03      f_04      f_05  \
0            0 -1.373246  0.238887 -0.243376  0.567405 -0.647715  0.839326   
1            1  1.697021 -1.710322 -2.230332 -0.545661  1.113173 -1.552175   
2            2  1.681726  0.616746 -1.027689  0.810492 -0.609086  0.113965   
3            3 -0.118172 -0.587835 -0.804638  2.086822  0.371005 -0.128831   
4            4  1.148481 -0.176567 -0.664871 -1.101343  0.467875  0.500117   
...        ...       ...       ...       ...       ...       ...       ...   
899995  899995  1.380145 -0.038884  0.597111  0.854560  0.684301 -1.058618   
899996  899996 -1.369789  0.044841  0.015458  0.376565 -0.380529 -0.830815   
899997  899997  1.386201 -0.961150  0.725994 -0.132844  0.873911 -0.245339   
899998  899998 -1.590572 -0.509938 -1.715397 -0.249988  1.359933  1.650808   
899999  899999 -0.636210 -0.425986 -1.826699 -0.598797  1.589577 -0.482298   

            f_06  f_07  f_08  ...      f_22      f_23      f_24      f_25  \
0       0.113133     1     5  ... -2.540739  0.766952 -2.730628 -0.208177   
1       0.447825     1     3  ...  2.278315 -0.633658 -1.217077 -3.782194   
2      -0.708660     1     0  ... -1.385775 -0.520558 -0.009121  2.788536   
3      -0.282575     3     2  ...  0.572594 -1.653213  1.686035 -2.533098   
4       0.407515     3     3  ... -3.912929 -1.430366  2.127649 -3.306784   
...          ...   ...   ...  ...       ...       ...       ...       ...   
899995  1.310699     2     1  ... -1.594744  0.522019  0.833047  2.714125   
899996 -1.798458     4     1  ...  2.413899 -0.674942 -0.412111 -0.030436   
899997 -1.045786     0     0  ... -0.151930 -4.560773 -1.249154  1.793535   
899998 -0.058592     0     2  ...  2.423670  2.110008  0.561271 -2.149610   
899999 -0.214093     7     1  ...  1.340696  3.762351  1.797137 -0.412837   

            f_26        f_28  f_29  f_30  target        f_27  
0       1.363402   67.609153     0     0       0  ABABDADBAB  
1      -0.058316  377.096415     0     0       1  ACACCADCEB  
2      -3.703488 -195.599702     0     2       1  AAAEABCKAD  
3      -0.608601  210.826205     0     0       1  BDBBAACBCB  
4       4.371371 -217.211798     0     1       1  BDBCBBCHFE  
...          ...         ...   ...   ...     ...         ...  
899995  1.290094  455.033851     0     2       1  BABBCBBBED  
899996 -3.144047  134.703577     0     1       0  BBBGBBDQBE  
899997  2.253696  -99.536313     0     1       0  AEBEDBBHBA  
899998  1.019982   47.823039     1     2       0  ADBAAADDAE  
899999  2.090440  -44.559296     0     2       1  BCAACADSCE  

[900000 rows x 33 columns]

In [4]:
#独立変数と従属変数に分ける
X1 = train_dataset.iloc[:, 1:-2].values
y1 = train_dataset.iloc[:, -2].values

In [5]:
X1

array([[-1.37324640e+00,  2.38887303e-01, -2.43376127e-01, ...,
         6.76091535e+01,  0.00000000e+00,  0.00000000e+00],
       [ 1.69702058e+00, -1.71032244e+00, -2.23033245e+00, ...,
         3.77096415e+02,  0.00000000e+00,  0.00000000e+00],
       [ 1.68172561e+00,  6.16745646e-01, -1.02768920e+00, ...,
        -1.95599702e+02,  0.00000000e+00,  2.00000000e+00],
       ...,
       [ 1.38620112e+00, -9.61150281e-01,  7.25994424e-01, ...,
        -9.95363133e+01,  0.00000000e+00,  1.00000000e+00],
       [-1.59057168e+00, -5.09937970e-01, -1.71539723e+00, ...,
         4.78230392e+01,  1.00000000e+00,  2.00000000e+00],
       [-6.36209999e-01, -4.25985956e-01, -1.82669907e+00, ...,
        -4.45592964e+01,  0.00000000e+00,  2.00000000e+00]])

In [6]:
y1

array([0, 1, 1, ..., 0, 0, 1])

In [7]:
X1[0, :]

array([-1.3732464 ,  0.2388873 , -0.24337613,  0.5674049 , -0.64771462,
        0.83932645,  0.11313285,  1.        ,  5.        ,  1.        ,
        3.        ,  3.        ,  3.        ,  1.        ,  6.        ,
        1.        ,  0.        ,  7.        ,  4.        ,  0.29821804,
       -0.91971679,  3.05854095, -2.54073888,  0.766952  , -2.73062823,
       -0.20817745,  1.3634024 , 67.60915349,  0.        ,  0.        ])

In [8]:
#フィチャースケーリング
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1[:, -3:-2] = sc.fit_transform(X1[:, -3:-2])

In [9]:
X1[0, :]

array([-1.3732464 ,  0.2388873 , -0.24337613,  0.5674049 , -0.64771462,
        0.83932645,  0.11313285,  1.        ,  5.        ,  1.        ,
        3.        ,  3.        ,  3.        ,  1.        ,  6.        ,
        1.        ,  0.        ,  7.        ,  4.        ,  0.29821804,
       -0.91971679,  3.05854095, -2.54073888,  0.766952  , -2.73062823,
       -0.20817745,  1.3634024 ,  0.28474766,  0.        ,  0.        ])

In [10]:
#データセットの分割
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=0)

In [12]:
#モデルの訓練
gbm = lgb.LGBMClassifier()
gbm.fit(X1_train, y1_train)

LGBMClassifier()

In [14]:
#結果の予測
y1_pred = gbm.predict(X1_test)
y1_pred_prob = gbm.predict_proba(X1_test)

In [15]:
df_pred = pd.DataFrame({'target':y1_test, 'target_pred':y1_pred})
display(df_pred)

target  target_pred
0            1            1
1            0            1
2            1            1
3            1            0
4            0            0
...        ...          ...
179995       0            1
179996       1            1
179997       0            1
179998       0            1
179999       0            0

[180000 rows x 2 columns]

In [16]:
df_pred_prob = pd.DataFrame({'target':y1_test, 'target0_prob':y1_pred_prob[:, 0], 'target1_prob':y1_pred_prob[:, 1]})
display(df_pred_prob)

target  target0_prob  target1_prob
0            1      0.239942      0.760058
1            0      0.491489      0.508511
2            1      0.118964      0.881036
3            1      0.507343      0.492657
4            0      0.527505      0.472495
...        ...           ...           ...
179995       0      0.430508      0.569492
179996       1      0.146779      0.853221
179997       0      0.447944      0.552056
179998       0      0.204589      0.795411
179999       0      0.790170      0.209830

[180000 rows x 3 columns]

In [17]:
#モデルの評価
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y1_test, y1_pred)
print(cm)
accuracy_score(y1_test, y1_pred)

[[76690 15580]
 [16978 70752]]


0.8191222222222222

In [18]:
test_dataset = pd.read_csv('test.csv')

In [19]:
test_dataset

id      f_00      f_01      f_02      f_03      f_04      f_05  \
0        900000  0.442517  0.174380 -0.999816  0.762741  0.186778 -1.074775   
1        900001 -0.605598 -0.305715  0.627667 -0.578898 -1.750931  1.355550   
2        900002  0.303990  2.445110  0.246515  0.818248  0.359731 -1.331845   
3        900003  0.154053  0.260126 -1.367092 -0.093175 -1.111034 -0.948481   
4        900004 -1.651904 -0.424266 -0.667356 -0.322124 -0.089462  0.181705   
...         ...       ...       ...       ...       ...       ...       ...   
699995  1599995  0.640110  0.897808 -0.523956  1.563760 -0.092281 -0.610867   
699996  1599996 -0.191771 -0.035246 -0.118533  0.584750  2.126977  0.568659   
699997  1599997 -0.331704 -0.328845 -1.185503  1.022128 -0.483099 -0.107146   
699998  1599998 -2.031073 -1.238398  0.964699 -1.045950  0.906064  0.634301   
699999  1599999 -0.085906 -0.002124  2.227375  0.217145  3.179153 -1.660188   

            f_06  f_07  f_08  ...      f_21      f_22      f_23      f_24  \
0       0.501888     6     6  ... -1.006400 -1.193879 -2.435736 -2.427430   
1      -0.190911     1     3  ...  2.382405  0.149442  1.883322 -2.848714   
2       1.358622     3     3  ... -7.026098  1.312277 -5.157192  1.714005   
3       1.119220     0     0  ... -0.594532 -3.939475  1.754570 -2.364007   
4       1.784983     2     2  ...  0.084906 -0.985736 -0.130467 -3.557893   
...          ...   ...   ...  ...       ...       ...       ...       ...   
699995  0.535426     0     1  ...  2.604048  1.122867  0.518110  1.243837   
699996 -0.052663     4     3  ...  3.029857  1.384682 -1.135740  2.982713   
699997 -0.968281     1     1  ...  4.021273 -1.845266  1.096011 -2.734508   
699998 -0.707474     5     1  ...  1.453864 -1.696606  1.018995  1.973697   
699999  0.891989     0     3  ... -3.549082 -4.325318 -5.017221  0.251268   

            f_25      f_26        f_28  f_29  f_30        f_27  
0      -1.966887  5.734205   99.478419     0     0  BAAABADLAC  
1      -0.725155  3.194219  -65.993825     1     0  AFABBAEGCB  
2       0.585032  0.066898  -87.405622     0     1  BBACABBKEE  
3      -1.003320  3.893099 -281.293460     0     0  AEBEAACQCC  
4       1.210687  1.861884   25.629415     0     2  AEBBBBDABF  
...          ...       ...         ...   ...   ...         ...  
699995  0.575111  0.076372  204.186539     0     0  BCBCEBHMCD  
699996 -1.511760  2.225218  -97.694591     0     2  BAABCADQFC  
699997 -4.885955 -2.248739  130.622745     1     0  AAAJCBGQBA  
699998 -0.353068 -3.333449 -364.625148     0     0  BCBBCABNDE  
699999 -3.236026 -0.362070 -155.417341     0     1  AFBEBACHFF  

[700000 rows x 32 columns]

In [20]:
X2 = test_dataset.iloc[:, 1:-1].values

In [21]:
#フィーチャースケーリング
X2[:, -3:-2] = sc.fit_transform(X2[:, -3:-2])

In [22]:
gbm.fit(X1, y1)

LGBMClassifier()

In [23]:
X2_pred = gbm.predict(X2)

In [24]:
X2_pred

array([1, 1, 0, ..., 0, 1, 0])

In [25]:
id = test_dataset.iloc[:, 0].values
df_id = pd.DataFrame({'id': id})

In [26]:
df_id

id
0        900000
1        900001
2        900002
3        900003
4        900004
...         ...
699995  1599995
699996  1599996
699997  1599997
699998  1599998
699999  1599999

[700000 rows x 1 columns]

In [27]:
df_pred_answer = pd.DataFrame({'target': X2_pred})

In [28]:
df_pred_answer

target
0            1
1            1
2            0
3            0
4            1
...        ...
699995       0
699996       1
699997       0
699998       1
699999       0

[700000 rows x 1 columns]

In [29]:
df = pd.concat([df_id, df_pred_answer], axis=1)

In [30]:
df

id  target
0        900000       1
1        900001       1
2        900002       0
3        900003       0
4        900004       1
...         ...     ...
699995  1599995       0
699996  1599996       1
699997  1599997       0
699998  1599998       1
699999  1599999       0

[700000 rows x 2 columns]

In [32]:
df.to_csv('tarbular_pred2.csv', index=False)