In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#データセットの読み込み
train_dataset = pd.read_csv('train.csv')

In [3]:
train_dataset

id      f_00      f_01      f_02      f_03      f_04      f_05  \
0            0 -1.373246  0.238887 -0.243376  0.567405 -0.647715  0.839326   
1            1  1.697021 -1.710322 -2.230332 -0.545661  1.113173 -1.552175   
2            2  1.681726  0.616746 -1.027689  0.810492 -0.609086  0.113965   
3            3 -0.118172 -0.587835 -0.804638  2.086822  0.371005 -0.128831   
4            4  1.148481 -0.176567 -0.664871 -1.101343  0.467875  0.500117   
...        ...       ...       ...       ...       ...       ...       ...   
899995  899995  1.380145 -0.038884  0.597111  0.854560  0.684301 -1.058618   
899996  899996 -1.369789  0.044841  0.015458  0.376565 -0.380529 -0.830815   
899997  899997  1.386201 -0.961150  0.725994 -0.132844  0.873911 -0.245339   
899998  899998 -1.590572 -0.509938 -1.715397 -0.249988  1.359933  1.650808   
899999  899999 -0.636210 -0.425986 -1.826699 -0.598797  1.589577 -0.482298   

            f_06  f_07  f_08  ...      f_22      f_23      f_24      f_25  \
0       0.113133     1     5  ... -2.540739  0.766952 -2.730628 -0.208177   
1       0.447825     1     3  ...  2.278315 -0.633658 -1.217077 -3.782194   
2      -0.708660     1     0  ... -1.385775 -0.520558 -0.009121  2.788536   
3      -0.282575     3     2  ...  0.572594 -1.653213  1.686035 -2.533098   
4       0.407515     3     3  ... -3.912929 -1.430366  2.127649 -3.306784   
...          ...   ...   ...  ...       ...       ...       ...       ...   
899995  1.310699     2     1  ... -1.594744  0.522019  0.833047  2.714125   
899996 -1.798458     4     1  ...  2.413899 -0.674942 -0.412111 -0.030436   
899997 -1.045786     0     0  ... -0.151930 -4.560773 -1.249154  1.793535   
899998 -0.058592     0     2  ...  2.423670  2.110008  0.561271 -2.149610   
899999 -0.214093     7     1  ...  1.340696  3.762351  1.797137 -0.412837   

            f_26        f_28  f_29  f_30  target        f_27  
0       1.363402   67.609153     0     0       0  ABABDADBAB  
1      -0.058316  377.096415     0     0       1  ACACCADCEB  
2      -3.703488 -195.599702     0     2       1  AAAEABCKAD  
3      -0.608601  210.826205     0     0       1  BDBBAACBCB  
4       4.371371 -217.211798     0     1       1  BDBCBBCHFE  
...          ...         ...   ...   ...     ...         ...  
899995  1.290094  455.033851     0     2       1  BABBCBBBED  
899996 -3.144047  134.703577     0     1       0  BBBGBBDQBE  
899997  2.253696  -99.536313     0     1       0  AEBEDBBHBA  
899998  1.019982   47.823039     1     2       0  ADBAAADDAE  
899999  2.090440  -44.559296     0     2       1  BCAACADSCE  

[900000 rows x 33 columns]

In [4]:
train_dataset.groupby('f_27').count

<bound method DataFrameGroupBy.count of <pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f8ae1e8ae80>>

In [5]:
train_dataset.isnull().sum()

id        0
f_00      0
f_01      0
f_02      0
f_03      0
f_04      0
f_05      0
f_06      0
f_07      0
f_08      0
f_09      0
f_10      0
f_11      0
f_12      0
f_13      0
f_14      0
f_15      0
f_16      0
f_17      0
f_18      0
f_19      0
f_20      0
f_21      0
f_22      0
f_23      0
f_24      0
f_25      0
f_26      0
f_28      0
f_29      0
f_30      0
target    0
f_27      0
dtype: int64

In [6]:
#独立変数と従属変数に分ける
X1 = train_dataset.iloc[:, 1:-2].values
y1 = train_dataset.iloc[:, -2].values

In [7]:
X1

array([[-1.37324640e+00,  2.38887303e-01, -2.43376127e-01, ...,
         6.76091535e+01,  0.00000000e+00,  0.00000000e+00],
       [ 1.69702058e+00, -1.71032244e+00, -2.23033245e+00, ...,
         3.77096415e+02,  0.00000000e+00,  0.00000000e+00],
       [ 1.68172561e+00,  6.16745646e-01, -1.02768920e+00, ...,
        -1.95599702e+02,  0.00000000e+00,  2.00000000e+00],
       ...,
       [ 1.38620112e+00, -9.61150281e-01,  7.25994424e-01, ...,
        -9.95363133e+01,  0.00000000e+00,  1.00000000e+00],
       [-1.59057168e+00, -5.09937970e-01, -1.71539723e+00, ...,
         4.78230392e+01,  1.00000000e+00,  2.00000000e+00],
       [-6.36209999e-01, -4.25985956e-01, -1.82669907e+00, ...,
        -4.45592964e+01,  0.00000000e+00,  2.00000000e+00]])

In [8]:
y1

array([0, 1, 1, ..., 0, 0, 1])

In [9]:
X1[0, :]

array([-1.3732464 ,  0.2388873 , -0.24337613,  0.5674049 , -0.64771462,
        0.83932645,  0.11313285,  1.        ,  5.        ,  1.        ,
        3.        ,  3.        ,  3.        ,  1.        ,  6.        ,
        1.        ,  0.        ,  7.        ,  4.        ,  0.29821804,
       -0.91971679,  3.05854095, -2.54073888,  0.766952  , -2.73062823,
       -0.20817745,  1.3634024 , 67.60915349,  0.        ,  0.        ])

In [10]:
#フィチャースケーリング
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1[:, 7:19] = sc.fit_transform(X1[:, 7:19])
X1[:, 27:] = sc.fit_transform(X1[:, 27:])

In [11]:
X1[0, :]

array([-1.3732464 ,  0.2388873 , -0.24337613,  0.5674049 , -0.64771462,
        0.83932645,  0.11313285, -0.62279787,  1.84920656, -0.83191461,
        0.49962782,  0.77828839,  0.08941664, -0.80587477,  3.29993699,
       -0.70176376, -1.34390225,  3.50314983,  1.23650971,  0.29821804,
       -0.91971679,  3.05854095, -2.54073888,  0.766952  , -2.73062823,
       -0.20817745,  1.3634024 ,  0.28474766, -0.72681502, -1.22425877])

In [12]:
#データセットの分割
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state = 0)

In [13]:
# #次元削減
# from sklearn.decomposition import PCA
# pca = PCA(n_components=5)
# X1_train = pca.fit_transform(X1_train)
# X1_test = pca.fit_transform(X1_test)

In [14]:
#モデルの訓練
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X1_train, y1_train)

LogisticRegression(random_state=0)

In [15]:
#結果の予測
y1_pred = classifier.predict(X1_test)

In [16]:
y1_pred

array([0, 1, 1, ..., 1, 1, 1])

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y1_test, y1_pred)
print(cm)
accuracy_score(y1_test, y1_pred)

[[60200 32070]
 [37198 50532]]


0.6151777777777778